### ISSUE TITLE
Unable to update status field for agent

### ISSUE THREAD

**Issue by mlisondra** [livechat/api-client-php#15]
I run the following curl command:

curl "https://api.livechatinc.com/agents/milder.lisondra@jewsforjesus.org" -u web@jewsforjesus.org:API_KEY -H X-API-Version:2 -X PUT -d "status=accepting+chats&max_chats_count=2"

However, the output I receive always returns the following JSON response.
Essentially, the field "status" is never updated.

{"login":"milder.lisondra@jewsforjesus.org","name":"Milder John Bernard Lisondra","login_status":"not accepting chats","permission":"administrator","daily_summary":0,"ticket_notifications":0,"job_title":"Support Agent","avatar":"livechat.s3.amazonaws.com/default/avatars/ab5b0666feffd67600206cd519fd77ea.jpg","notifications":{"new_visitor":0,"returning_visitor":0,"queued_visitor":1,"visitor_is_typing":0,"new_goal":1,"incoming_chat":1},"max_chats_count":2,"mute_all_sounds":0,"repeat_sound_notifications":0,"work_scheduler":{},"groups":[{"id":9,"name":"Testing"}],"status":"offline","last_logout":1436561366}

**Comment by morus12** [comment]
Hi!
If previous agent's status was 'offline', you can't simply log agent in. Status changes affects only logged in agents (with statuses 'accepting chats' or 'not accepting chats'). 

I agree it was confusing, that's why we've already updated the docs.
http://developers.livechatinc.com/rest-api/#update-agent

**Comment by mlisondra** [comment]
Thank you!
